export const GET_ALL_DRIVERS = 'GET_ALL_DRIVERS';
export const GET_DRIVERS_PER_PAGE = 'GET_DRIVERS_PER_PAGE';

export const GET_DRIVERS_BY_NAME = 'GET_DRIVERS_BY_NAME';
export const CLEAN_DRIVERS_BY_NAME = 'CLEAN_DRIVERS_BY_NAME';

export const GET_DRIVER_DETAIL = 'GET_DRIVER_DETAIL';
export const CLEAN_DRIVER_DETAIL = 'CLEAN_DRIVER_DETAIL';

export const FILTER_DRIVERS_BY_TEAMS = 'FILTER_DRIVERS_BY_TEAMS';
export const FILTER_DRIVERS_BY_ORIGIN = 'FILTER_DRIVERS_BY_ORIGIN';

export const ORDER_DRIVERS_BY_NAME = 'ORDER_DRIVERS_BY_NAME';
export const ORDER_DRIVERS_BY_BIRTHDATE = 'ORDER_DRIVERS_BY_BIRTHDATE';
