export const GET_ALL_DRIVERS = 'GET_ALL_DRIVERS';
export const GET_DRIVERS_PER_PAGE = 'GET_DRIVERS_PER_PAGE';

export const GET_DRIVERS_BY_NAME = 'GET_DRIVERS_BY_NAME';
export const CLEAN_DRIVERS_BY_NAME = 'CLEAN_DRIVERS_BY_NAME';

export const GET_DRIVER_DETAIL = 'GET_DRIVER_DETAIL';
export const CLEAN_DRIVER_DETAIL = 'CLEAN_DRIVER_DETAIL';

export const FILTER_DRIVERS_BY_TEAMS = 'FILTER_DRIVERS_BY_TEAMS';
export const FILTER_DRIVERS_BY_ORIGIN = 'FILTER_DRIVERS_BY_ORIGIN';

export const ORDER_DRIVERS_BY_NAME = 'ORDER_DRIVERS_BY_NAME';
export const ORDER_DRIVERS_BY_BIRTHDATE = 'ORDER_DRIVERS_BY_BIRTHDATE';

export const CREATE_DRIVER = 'CREATE_DRIVER';
export const CLEAR_CREATE_MESSAGE = 'CLEAR_CREATE_MESSAGE';

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_SEARCH = 'SET_SEARCH';
export const SET_PAGES_PAGINATION = 'SET_PAGES_PAGINATION';

export const GET_ALL_TEAMS = 'GET_ALL_TEAMS';